
[brick]
name = "Factorial_Chapel"
version = "0.0.0"
chplVersion = "1.22.1"
authors = ["Russel Winder <russel@winder.org.uk>"]

[dependencies]

[dev-dependencies]

[dev-dependencies.dev-dependencies]
